---
server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  datasource:
    url: ${BACKEND_DB_URL}
    username: ${BACKEND_DB_USERNAME}
    password: ${BACKEND_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect